CREATE TABLE IF NOT EXISTS `CATEGORIES_TV_SHOWS`
    (
    `CATEGORY_ID` BIGINT(20)  NOT NULL,
    `TV_SHOW_ID` BIGINT(20)  NOT NULL,
    PRIMARY KEY (`CATEGORY_ID`, `TV_SHOW_ID`),
    CONSTRAINT `CATEGORIES_TV_SHOWS_IBFK_1`
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
    CONSTRAINT `CATEGORIES_TV_SHOWS_IBFK_2`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES TV_SHOWS (ID)
    );

ALTER TABLE TV_SHOWS DROP COLUMN CATEGORY_ID;